# Generated by Django 5.2.8 on 2025-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ProductID', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
